// Self-contained emoji dataset for the picker — native Unicode chars (rendered
// by the OS font) plus search keywords. No external library or remote assets,
// so it works offline and under a strict CSP.

export interface EmojiCategory {
  id: string;
  name: string;
  /** tab icon (an emoji) */
  icon: string;
  /** [char, "space separated search keywords"] */
  emojis: Array<readonly [string, string]>;
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      ['😀', 'grinning face smile happy'], ['😃', 'smiley happy joy'], ['😄', 'laugh happy'],
      ['😁', 'grin beaming'], ['😆', 'laughing satisfied'], ['😅', 'sweat smile relief'],
      ['🤣', 'rofl rolling laughing'], ['😂', 'joy tears laughing lol'], ['🙂', 'slight smile'],
      ['🙃', 'upside down silly'], ['😉', 'wink'], ['😊', 'blush smile happy'],
      ['😇', 'innocent halo angel'], ['🥰', 'love hearts adore'], ['😍', 'heart eyes love'],
      ['🤩', 'star struck excited'], ['😘', 'kiss blow'], ['😗', 'kissing'], ['😚', 'kiss closed'],
      ['😙', 'kiss smile'], ['😋', 'yum tasty savouring'], ['😛', 'tongue out'],
      ['😜', 'wink tongue playful'], ['🤪', 'zany crazy goofy'], ['😝', 'tongue squint'],
      ['🤑', 'money mouth rich'], ['🤗', 'hug hugging'], ['🤭', 'giggle hand mouth'],
      ['🤫', 'shush quiet secret'], ['🤔', 'thinking hmm'], ['🤐', 'zipper mouth'],
      ['🤨', 'raised eyebrow suspicious'], ['😐', 'neutral meh'], ['😑', 'expressionless'],
      ['😶', 'no mouth speechless'], ['😏', 'smirk sly'], ['😒', 'unamused annoyed'],
      ['🙄', 'eye roll'], ['😬', 'grimace awkward'], ['🤥', 'lying pinocchio'],
      ['😌', 'relieved calm'], ['😔', 'pensive sad'], ['😪', 'sleepy tired'], ['🤤', 'drool'],
      ['😴', 'sleep zzz'], ['😷', 'mask sick'], ['🤒', 'sick thermometer'], ['🤕', 'hurt bandage'],
      ['🤢', 'nausea sick gross'], ['🤮', 'vomit puke'], ['🤧', 'sneeze'], ['🥵', 'hot heat'],
      ['🥶', 'cold freezing'], ['🥴', 'woozy drunk'], ['😵', 'dizzy knocked out'],
      ['🤯', 'mind blown shocked'], ['🤠', 'cowboy'], ['🥳', 'party celebrate hat'],
      ['😎', 'cool sunglasses'], ['🤓', 'nerd geek'], ['🧐', 'monocle curious'],
      ['😕', 'confused'], ['😟', 'worried'], ['🙁', 'frown slight'], ['☹️', 'frown sad'],
      ['😮', 'open mouth wow surprise'], ['😯', 'hushed'], ['😲', 'astonished shocked'],
      ['😳', 'flushed embarrassed'], ['🥺', 'pleading puppy beg'], ['😦', 'frowning'],
      ['😧', 'anguished'], ['😨', 'fearful scared'], ['😰', 'anxious sweat'], ['😥', 'sad relieved'],
      ['😢', 'cry tear'], ['😭', 'sob crying loud'], ['😱', 'scream fear munch'],
      ['😖', 'confounded'], ['😣', 'persevere'], ['😞', 'disappointed'], ['😓', 'downcast sweat'],
      ['😩', 'weary'], ['😫', 'tired'], ['🥱', 'yawn bored'], ['😤', 'triumph steam huff'],
      ['😡', 'angry mad rage red'], ['😠', 'angry'], ['🤬', 'cursing swearing symbols'],
      ['😈', 'devil smiling horns'], ['👿', 'imp angry devil'], ['💀', 'skull dead'],
      ['💩', 'poop crap'], ['🤡', 'clown'], ['👻', 'ghost boo'], ['👽', 'alien'], ['🤖', 'robot'],
    ],
  },
  {
    id: 'people',
    name: 'People & Body',
    icon: '👍',
    emojis: [
      ['👋', 'wave hi hello bye'], ['🤚', 'raised back hand'], ['✋', 'raised hand stop high five'],
      ['🖖', 'vulcan spock'], ['👌', 'ok perfect'], ['🤌', 'pinched fingers italian'],
      ['🤏', 'pinch small tiny'], ['✌️', 'victory peace'], ['🤞', 'fingers crossed luck'],
      ['🤟', 'love you sign'], ['🤘', 'rock horns metal'], ['🤙', 'call me shaka'],
      ['👈', 'point left'], ['👉', 'point right'], ['👆', 'point up'], ['👇', 'point down'],
      ['☝️', 'index up'], ['👍', 'thumbs up like yes good'], ['👎', 'thumbs down dislike no bad'],
      ['✊', 'fist raised'], ['👊', 'fist punch bump'], ['🤛', 'fist left'], ['🤜', 'fist right'],
      ['👏', 'clap applause bravo'], ['🙌', 'raised hands praise hooray'], ['👐', 'open hands'],
      ['🤲', 'palms up together'], ['🤝', 'handshake deal agreement'], ['🙏', 'pray thanks please hope'],
      ['✍️', 'writing hand'], ['💅', 'nail polish'], ['🤳', 'selfie'], ['💪', 'muscle strong flex'],
      ['🦵', 'leg'], ['🦶', 'foot'], ['👂', 'ear'], ['👃', 'nose'], ['🧠', 'brain smart'],
      ['👀', 'eyes look see'], ['👁️', 'eye'], ['👅', 'tongue'], ['👄', 'mouth lips'],
      ['💋', 'kiss lips mark'], ['👶', 'baby'], ['🧒', 'child'], ['👦', 'boy'], ['👧', 'girl'],
      ['🧑', 'person adult'], ['👨', 'man'], ['👩', 'woman'], ['🧓', 'older person'],
      ['👴', 'old man grandpa'], ['👵', 'old woman grandma'], ['🙅', 'no gesture forbidden'],
      ['🙆', 'ok gesture'], ['💁', 'info desk tipping hand sassy'], ['🙋', 'raising hand question'],
      ['🙇', 'bow sorry'], ['🤦', 'facepalm'], ['🤷', 'shrug dunno idk'], ['👮', 'police cop'],
      ['🕵️', 'detective spy'], ['💂', 'guard'], ['👷', 'construction worker'], ['🤴', 'prince'],
      ['👸', 'princess'], ['🎅', 'santa claus'], ['🦸', 'superhero'], ['🦹', 'supervillain'],
      ['🧙', 'mage wizard'], ['🧚', 'fairy'], ['🧛', 'vampire'], ['🧜', 'mermaid merperson'],
      ['🧟', 'zombie'], ['🚶', 'walk pedestrian'], ['🏃', 'run running'], ['💃', 'dance woman'],
      ['🕺', 'dance man'], ['👫', 'couple holding hands'], ['👪', 'family'],
      ['❤️', 'heart love red'], ['🧡', 'orange heart'], ['💛', 'yellow heart'], ['💚', 'green heart'],
      ['💙', 'blue heart'], ['💜', 'purple heart'], ['🖤', 'black heart'], ['🤍', 'white heart'],
      ['🤎', 'brown heart'], ['💔', 'broken heart heartbreak'], ['💕', 'two hearts'],
      ['💞', 'revolving hearts'], ['💓', 'beating heart'], ['💗', 'growing heart'],
      ['💖', 'sparkling heart'], ['💘', 'cupid arrow heart'], ['💝', 'heart gift ribbon'],
      ['💌', 'love letter'], ['💯', 'hundred perfect score'], ['💢', 'anger symbol'],
      ['💥', 'boom collision explode'], ['💫', 'dizzy stars'], ['💦', 'sweat drops splash'],
      ['💨', 'dash wind fast'], ['💬', 'speech bubble comment'], ['💭', 'thought bubble'],
      ['💤', 'zzz sleep'],
    ],
  },
  {
    id: 'nature',
    name: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      ['🐶', 'dog puppy'], ['🐱', 'cat kitten'], ['🐭', 'mouse'], ['🐹', 'hamster'],
      ['🐰', 'rabbit bunny'], ['🦊', 'fox'], ['🐻', 'bear'], ['🐼', 'panda'], ['🐨', 'koala'],
      ['🐯', 'tiger'], ['🦁', 'lion'], ['🐮', 'cow'], ['🐷', 'pig'], ['🐸', 'frog'],
      ['🐵', 'monkey'], ['🐔', 'chicken'], ['🐧', 'penguin'], ['🐦', 'bird'], ['🐤', 'chick baby'],
      ['🦆', 'duck'], ['🦅', 'eagle'], ['🦉', 'owl'], ['🦇', 'bat'], ['🐺', 'wolf'],
      ['🐗', 'boar'], ['🐴', 'horse'], ['🦄', 'unicorn'], ['🐝', 'bee honeybee'],
      ['🐛', 'bug caterpillar'], ['🦋', 'butterfly'], ['🐌', 'snail'], ['🐞', 'ladybug'],
      ['🐜', 'ant'], ['🕷️', 'spider'], ['🐢', 'turtle'], ['🐍', 'snake'], ['🦎', 'lizard'],
      ['🐙', 'octopus'], ['🦑', 'squid'], ['🦐', 'shrimp'], ['🦀', 'crab'], ['🐠', 'tropical fish'],
      ['🐟', 'fish'], ['🐬', 'dolphin'], ['🐳', 'whale spouting'], ['🦈', 'shark'],
      ['🐊', 'crocodile'], ['🦓', 'zebra'], ['🦍', 'gorilla'], ['🐘', 'elephant'],
      ['🦛', 'hippo'], ['🦏', 'rhino'], ['🐪', 'camel'], ['🦒', 'giraffe'], ['🐑', 'sheep'],
      ['🐐', 'goat'], ['🦌', 'deer'], ['🐕', 'dog'], ['🐈', 'cat'], ['🦃', 'turkey'],
      ['🕊️', 'dove peace'], ['🐿️', 'chipmunk squirrel'], ['🌵', 'cactus'], ['🎄', 'christmas tree'],
      ['🌲', 'evergreen tree'], ['🌳', 'tree'], ['🌴', 'palm tree'], ['🌱', 'seedling sprout'],
      ['🌿', 'herb plant'], ['☘️', 'shamrock'], ['🍀', 'four leaf clover luck'], ['🍃', 'leaves'],
      ['🍂', 'fallen leaves autumn'], ['🍁', 'maple leaf'], ['🌾', 'wheat'], ['🌷', 'tulip'],
      ['🌹', 'rose'], ['🥀', 'wilted flower'], ['🌺', 'hibiscus'], ['🌸', 'cherry blossom flower'],
      ['🌼', 'blossom flower'], ['🌻', 'sunflower'], ['🌞', 'sun face'], ['🌝', 'full moon face'],
      ['🌚', 'new moon face'], ['🌕', 'full moon'], ['🌙', 'crescent moon'], ['⭐', 'star'],
      ['🌟', 'glowing star'], ['✨', 'sparkles shiny'], ['⚡', 'lightning bolt'], ['☄️', 'comet'],
      ['🔥', 'fire lit flame hot'], ['🌈', 'rainbow'], ['☀️', 'sun sunny'], ['⛅', 'sun cloud'],
      ['☁️', 'cloud'], ['🌧️', 'rain'], ['⛈️', 'thunderstorm'], ['❄️', 'snowflake cold'],
      ['☃️', 'snowman'], ['💧', 'droplet water'], ['🌊', 'wave ocean water'],
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: '🍔',
    emojis: [
      ['🍎', 'apple red'], ['🍏', 'green apple'], ['🍐', 'pear'], ['🍊', 'orange tangerine'],
      ['🍋', 'lemon'], ['🍌', 'banana'], ['🍉', 'watermelon'], ['🍇', 'grapes'],
      ['🍓', 'strawberry'], ['🫐', 'blueberry'], ['🍒', 'cherries'], ['🍑', 'peach'],
      ['🥭', 'mango'], ['🍍', 'pineapple'], ['🥥', 'coconut'], ['🥝', 'kiwi'], ['🍅', 'tomato'],
      ['🍆', 'eggplant aubergine'], ['🥑', 'avocado'], ['🥦', 'broccoli'], ['🥬', 'lettuce greens'],
      ['🥒', 'cucumber'], ['🌶️', 'hot pepper spicy chili'], ['🌽', 'corn'], ['🥕', 'carrot'],
      ['🧄', 'garlic'], ['🧅', 'onion'], ['🥔', 'potato'], ['🍠', 'sweet potato'],
      ['🥐', 'croissant'], ['🍞', 'bread'], ['🥖', 'baguette'], ['🥨', 'pretzel'], ['🧀', 'cheese'],
      ['🥚', 'egg'], ['🍳', 'fried egg cooking'], ['🥞', 'pancakes'], ['🧇', 'waffle'],
      ['🥓', 'bacon'], ['🥩', 'steak meat'], ['🍗', 'poultry leg chicken'], ['🍖', 'meat bone'],
      ['🌭', 'hot dog'], ['🍔', 'burger hamburger'], ['🍟', 'fries chips'], ['🍕', 'pizza'],
      ['🥪', 'sandwich'], ['🌮', 'taco'], ['🌯', 'burrito'], ['🥗', 'salad'], ['🍝', 'pasta spaghetti'],
      ['🍜', 'ramen noodles'], ['🍲', 'stew hotpot'], ['🍛', 'curry rice'], ['🍣', 'sushi'],
      ['🍱', 'bento box'], ['🥟', 'dumpling'], ['🍤', 'fried shrimp tempura'], ['🍙', 'rice ball'],
      ['🍚', 'rice'], ['🍦', 'soft serve ice cream'], ['🍨', 'ice cream'], ['🍧', 'shaved ice'],
      ['🥧', 'pie'], ['🧁', 'cupcake'], ['🍰', 'cake slice shortcake'], ['🎂', 'birthday cake'],
      ['🍮', 'custard pudding'], ['🍭', 'lollipop'], ['🍬', 'candy sweet'], ['🍫', 'chocolate'],
      ['🍿', 'popcorn'], ['🍩', 'donut doughnut'], ['🍪', 'cookie'], ['🌰', 'chestnut'],
      ['🥜', 'peanuts nuts'], ['🍯', 'honey'], ['🥛', 'milk glass'], ['🍼', 'baby bottle'],
      ['☕', 'coffee tea hot'], ['🍵', 'tea green'], ['🧃', 'juice box'], ['🥤', 'soda cup drink'],
      ['🍶', 'sake'], ['🍺', 'beer'], ['🍻', 'beers cheers'], ['🥂', 'champagne cheers toast'],
      ['🍷', 'wine'], ['🥃', 'whiskey glass'], ['🍸', 'cocktail martini'], ['🍹', 'tropical drink'],
      ['🍾', 'champagne bottle'], ['🧊', 'ice cube'],
    ],
  },
  {
    id: 'activities',
    name: 'Activities',
    icon: '⚽',
    emojis: [
      ['⚽', 'soccer football'], ['🏀', 'basketball'], ['🏈', 'american football'],
      ['⚾', 'baseball'], ['🥎', 'softball'], ['🎾', 'tennis'], ['🏐', 'volleyball'],
      ['🏉', 'rugby'], ['🎱', 'pool 8 ball billiards'], ['🏓', 'ping pong table tennis'],
      ['🏸', 'badminton'], ['🥅', 'goal net'], ['🏒', 'ice hockey'], ['🏑', 'field hockey'],
      ['🏏', 'cricket'], ['⛳', 'golf flag'], ['🏹', 'bow arrow archery'], ['🎣', 'fishing'],
      ['🥊', 'boxing glove'], ['🥋', 'martial arts karate'], ['⛸️', 'ice skate'], ['🎿', 'ski'],
      ['🏂', 'snowboard'], ['🏋️', 'weight lifting gym'], ['🤼', 'wrestling'], ['🤸', 'cartwheel gymnastics'],
      ['🤺', 'fencing'], ['🏌️', 'golfer golf'], ['🏇', 'horse racing'], ['🧘', 'yoga meditate zen'],
      ['🏄', 'surf'], ['🏊', 'swim'], ['🚣', 'rowing boat'], ['🧗', 'climbing'],
      ['🚵', 'mountain biking'], ['🚴', 'cycling bike'], ['🏆', 'trophy win champion'],
      ['🥇', 'gold medal first'], ['🥈', 'silver medal second'], ['🥉', 'bronze medal third'],
      ['🏅', 'medal'], ['🎖️', 'military medal'], ['🎗️', 'reminder ribbon'], ['🎫', 'ticket'],
      ['🎪', 'circus tent'], ['🤹', 'juggling'], ['🎭', 'performing arts theater masks'],
      ['🎨', 'art palette painting'], ['🎬', 'clapper movie film'], ['🎤', 'microphone sing karaoke'],
      ['🎧', 'headphones music'], ['🎼', 'musical score'], ['🎹', 'piano keyboard'],
      ['🥁', 'drum'], ['🎷', 'saxophone'], ['🎺', 'trumpet'], ['🎸', 'guitar'], ['🎻', 'violin'],
      ['🎲', 'dice game'], ['♟️', 'chess pawn'], ['🎯', 'dart bullseye target'], ['🎳', 'bowling'],
      ['🎮', 'video game controller'], ['🕹️', 'joystick'], ['🎰', 'slot machine'], ['🧩', 'puzzle piece'],
    ],
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    icon: '🚗',
    emojis: [
      ['🚗', 'car auto'], ['🚕', 'taxi cab'], ['🚙', 'suv'], ['🚌', 'bus'], ['🏎️', 'race car'],
      ['🚓', 'police car'], ['🚑', 'ambulance'], ['🚒', 'fire truck'], ['🚚', 'truck delivery'],
      ['🚛', 'lorry semi truck'], ['🚜', 'tractor'], ['🛴', 'kick scooter'], ['🚲', 'bike bicycle'],
      ['🛵', 'motor scooter'], ['🏍️', 'motorcycle'], ['🚨', 'siren police light'],
      ['🚄', 'bullet train'], ['🚅', 'shinkansen train'], ['🚂', 'locomotive steam train'],
      ['🚆', 'train'], ['🚇', 'metro subway'], ['🚊', 'tram'], ['🚉', 'station'],
      ['✈️', 'airplane flight travel'], ['🛫', 'plane departure takeoff'], ['🛬', 'plane arrival landing'],
      ['💺', 'seat'], ['🚁', 'helicopter'], ['🚀', 'rocket launch space'], ['🛸', 'ufo flying saucer'],
      ['🚤', 'speedboat'], ['⛵', 'sailboat'], ['🚢', 'ship cruise'], ['⚓', 'anchor'],
      ['⛽', 'fuel gas station'], ['🚧', 'construction barrier'], ['🚦', 'traffic light'],
      ['🗺️', 'world map'], ['🗿', 'moai statue'], ['🗽', 'statue of liberty'], ['🗼', 'tokyo tower'],
      ['🏰', 'castle'], ['🏯', 'japanese castle'], ['🎡', 'ferris wheel'], ['🎢', 'roller coaster'],
      ['🎠', 'carousel merry go round'], ['⛲', 'fountain'], ['⛱️', 'beach umbrella'],
      ['🏖️', 'beach'], ['🏝️', 'desert island'], ['🏜️', 'desert'], ['🌋', 'volcano'],
      ['⛰️', 'mountain'], ['🏔️', 'snowy mountain'], ['🗻', 'mount fuji'], ['🏕️', 'camping'],
      ['⛺', 'tent'], ['🏠', 'house home'], ['🏡', 'house garden'], ['🏢', 'office building'],
      ['🏥', 'hospital'], ['🏦', 'bank'], ['🏨', 'hotel'], ['🏪', 'convenience store'],
      ['🏫', 'school'], ['⛪', 'church'], ['🕌', 'mosque'], ['🛕', 'temple hindu'],
      ['🕍', 'synagogue'], ['⛩️', 'shrine torii'], ['🌃', 'night stars city'],
      ['🏙️', 'cityscape city'], ['🌄', 'sunrise mountains'], ['🌅', 'sunrise'],
      ['🌆', 'city dusk'], ['🌇', 'sunset'], ['🌉', 'bridge night'], ['🎇', 'sparkler fireworks'],
      ['🎆', 'fireworks'], ['🌌', 'milky way galaxy stars'],
    ],
  },
  {
    id: 'objects',
    name: 'Objects',
    icon: '💡',
    emojis: [
      ['⌚', 'watch'], ['📱', 'phone mobile smartphone'], ['💻', 'laptop computer'],
      ['⌨️', 'keyboard'], ['🖥️', 'desktop computer'], ['🖨️', 'printer'], ['🖱️', 'mouse computer'],
      ['💾', 'floppy disk save'], ['💿', 'cd disc'], ['📷', 'camera photo'], ['📸', 'camera flash'],
      ['📹', 'video camera'], ['🎥', 'movie camera film'], ['📞', 'phone receiver call'],
      ['☎️', 'telephone'], ['📺', 'tv television'], ['📻', 'radio'], ['⏰', 'alarm clock'],
      ['⏱️', 'stopwatch'], ['⌛', 'hourglass done'], ['⏳', 'hourglass flowing'], ['📡', 'satellite antenna'],
      ['🔋', 'battery'], ['🔌', 'plug electric'], ['💡', 'light bulb idea'], ['🔦', 'flashlight torch'],
      ['🕯️', 'candle'], ['🧯', 'fire extinguisher'], ['💸', 'money flying cash'], ['💵', 'dollar money'],
      ['💰', 'money bag'], ['💳', 'credit card'], ['💎', 'gem diamond'], ['⚖️', 'balance scales justice'],
      ['🔧', 'wrench tool'], ['🔨', 'hammer'], ['🛠️', 'tools hammer wrench'], ['🔩', 'nut bolt'],
      ['⚙️', 'gear settings cog'], ['🧲', 'magnet'], ['💣', 'bomb'], ['🧨', 'firecracker dynamite'],
      ['🔪', 'knife cut'], ['🗡️', 'dagger'], ['⚔️', 'crossed swords'], ['🛡️', 'shield'],
      ['🔮', 'crystal ball fortune'], ['🧿', 'nazar evil eye'], ['🔭', 'telescope'], ['🔬', 'microscope'],
      ['💊', 'pill medicine'], ['💉', 'syringe shot vaccine'], ['🩹', 'bandage plaster'],
      ['🩺', 'stethoscope'], ['🌡️', 'thermometer'], ['🧬', 'dna'], ['🦠', 'microbe germ virus'],
      ['🧪', 'test tube science'], ['🚽', 'toilet'], ['🚿', 'shower'], ['🛁', 'bathtub'],
      ['🧴', 'lotion soap bottle'], ['🧹', 'broom sweep'], ['🧺', 'basket laundry'],
      ['🧻', 'toilet paper roll'], ['🧼', 'soap'], ['🧽', 'sponge'], ['🔑', 'key'],
      ['🗝️', 'old key'], ['🚪', 'door'], ['🛋️', 'couch sofa'], ['🛏️', 'bed'], ['🖼️', 'framed picture'],
      ['🛍️', 'shopping bags'], ['🛒', 'shopping cart trolley'], ['🎁', 'gift present'],
      ['🎈', 'balloon'], ['🎀', 'ribbon bow'], ['🎉', 'party popper tada celebrate'],
      ['🎊', 'confetti ball'], ['🏮', 'red lantern'], ['✉️', 'envelope mail email'],
      ['📩', 'incoming envelope'], ['📧', 'email e-mail'], ['📦', 'package box parcel'],
      ['🏷️', 'label tag'], ['📮', 'postbox'], ['📝', 'memo note write'], ['📄', 'page document'],
      ['📊', 'bar chart graph'], ['📈', 'chart increasing up'], ['📉', 'chart decreasing down'],
      ['📅', 'calendar date'], ['📋', 'clipboard'], ['📌', 'pushpin'], ['📍', 'round pin location'],
      ['📎', 'paperclip attach'], ['✂️', 'scissors cut'], ['📏', 'ruler'], ['🗓️', 'calendar spiral'],
      ['📕', 'closed book'], ['📚', 'books stack'], ['📖', 'open book read'], ['🔖', 'bookmark'],
      ['🔗', 'link chain'], ['📰', 'newspaper news'], ['🔍', 'magnifying glass search'],
      ['🔒', 'lock closed secure'], ['🔓', 'unlock open'], ['🔐', 'lock key secure'],
      ['✏️', 'pencil write'], ['🖊️', 'pen'], ['🖌️', 'paintbrush'], ['🖍️', 'crayon'],
    ],
  },
  {
    id: 'symbols',
    name: 'Symbols',
    icon: '❤️',
    emojis: [
      ['✅', 'check yes done tick'], ['❌', 'cross no x wrong'], ['❎', 'negative squared'],
      ['➕', 'plus add'], ['➖', 'minus subtract'], ['➗', 'divide'], ['✖️', 'multiply times'],
      ['♾️', 'infinity forever'], ['❗', 'exclamation bang'], ['❓', 'question mark'],
      ['⚠️', 'warning caution'], ['🚸', 'children crossing'], ['🔞', 'no under 18 adult'],
      ['📵', 'no phones'], ['🚭', 'no smoking'], ['💲', 'dollar sign'], ['™️', 'trademark tm'],
      ['©️', 'copyright'], ['®️', 'registered'], ['🔴', 'red circle'], ['🟠', 'orange circle'],
      ['🟡', 'yellow circle'], ['🟢', 'green circle'], ['🔵', 'blue circle'], ['🟣', 'purple circle'],
      ['⚫', 'black circle'], ['⚪', 'white circle'], ['🟥', 'red square'], ['🟩', 'green square'],
      ['🟦', 'blue square'], ['⬛', 'black large square'], ['⬜', 'white large square'],
      ['🔺', 'red triangle up'], ['🔻', 'red triangle down'], ['🔶', 'orange diamond'],
      ['🔷', 'blue diamond'], ['💠', 'diamond dot'], ['🔔', 'bell notification'], ['🔕', 'no bell mute'],
      ['📢', 'loudspeaker announce'], ['📣', 'megaphone cheer'], ['🔊', 'speaker loud volume'],
      ['🔇', 'mute speaker'], ['🌐', 'globe web internet'], ['♻️', 'recycle'], ['🔱', 'trident'],
      ['⭕', 'circle o'], ['✳️', 'eight spoked asterisk'], ['✴️', 'star eight'], ['❇️', 'sparkle'],
      ['✔️', 'check mark tick'], ['☑️', 'check box ballot'], ['🔘', 'radio button'],
      ['▶️', 'play'], ['⏸️', 'pause'], ['⏹️', 'stop'], ['⏭️', 'next track'], ['⏮️', 'previous track'],
      ['🔀', 'shuffle'], ['🔁', 'repeat loop'], ['🔂', 'repeat one'], ['🔄', 'refresh sync arrows'],
      ['➡️', 'right arrow'], ['⬅️', 'left arrow'], ['⬆️', 'up arrow'], ['⬇️', 'down arrow'],
      ['↔️', 'left right arrow'], ['↕️', 'up down arrow'], ['🔝', 'top up'], ['🆗', 'ok button'],
      ['🆕', 'new'], ['🆒', 'cool'], ['🆓', 'free'], ['🔟', 'ten keycap'], ['#️⃣', 'hash number'],
      ['1️⃣', 'one'], ['2️⃣', 'two'], ['3️⃣', 'three'], ['💤', 'zzz sleep'], ['💢', 'anger'],
      ['💯', 'hundred perfect'], ['🚫', 'prohibited no forbidden'], ['🔰', 'beginner'],
      ['⚜️', 'fleur de lis'], ['〽️', 'part alternation'], ['💮', 'white flower'], ['🏵️', 'rosette'],
    ],
  },
];

const RECENT_KEY = 'fbclone:recent-emojis';
const RECENT_MAX = 24;

/** Read the recent-emoji list from localStorage (most-recent first). */
export function getRecentEmojis(): string[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = window.localStorage.getItem(RECENT_KEY);
    const arr = raw ? (JSON.parse(raw) as unknown) : [];
    return Array.isArray(arr) ? arr.filter((x): x is string => typeof x === 'string').slice(0, RECENT_MAX) : [];
  } catch {
    return [];
  }
}

/** Record an emoji as recently used and return the updated list. */
export function pushRecentEmoji(emoji: string): string[] {
  const next = [emoji, ...getRecentEmojis().filter((e) => e !== emoji)].slice(0, RECENT_MAX);
  try {
    window.localStorage.setItem(RECENT_KEY, JSON.stringify(next));
  } catch {
    /* ignore quota / privacy-mode errors */
  }
  return next;
}
